### ISSUE TITLE
Issue with 3SHAKE detection

### ISSUE THREAD

**Issue by pm-cfs** [stfbk/tlsassistant#5]
The text2html module used results in fixed width text files; some tags may break across two lines.
The test for 3SHAKE invovles looking for "extended master secret/#23" using a negative grep. If that TLS extension tag breaks across two lines, you'll get a false positive from `Evaluator/enumerator.sh`.

A multiline with regex grep option works properly as shown below.

```
    #3SHAKE
    if ! grep -Pzq "extended[\n| ]master[\n| ]secret/#23" $toolReports/testssl_report.txt ; then
        echo "3SHAKE">> $root_folder/vulnerabilityList.txt
        echo "- detected: 3SHAKE"
    fi
```

**Comment by matteounitn** [comment]
Thanks for the report, we will test it asap and update the code.

**Comment by matteounitn** [comment]
> The text2html module used results in fixed width text files; some tags may break across two lines.
> The test for 3SHAKE invovles looking for "extended master secret/#23" using a negative grep. If that TLS extension tag breaks across two lines, you'll get a false positive from `Evaluator/enumerator.sh`.
> 
> A multiline with regex grep option works properly as shown below.
> 
> ```
>     #3SHAKE
>     if ! grep -Pzq "extended[\n| ]master[\n| ]secret/#23" $toolReports/testssl_report.txt ; then
>         echo "3SHAKE">> $root_folder/vulnerabilityList.txt
>         echo "- detected: 3SHAKE"
>     fi
> ```

To speedup the process, can you kindly provide an example url where the problem occurs?

**Comment by pm-cfs** [comment]
Sorry, it's an internal system; I don't have a publically accessible URL.
I can provide a scrubbed version of the testssl.sh HTML output (or the html2text Text version).

Here's an example of the text output:
```
 Testing server defaults (Server Hello)

 TLS extensions (standard)    "renegotiation info/#65281" "EC point formats/
#11"
                              "session ticket/#35" "heartbeat/#15" "extended
master secret/#23"
 Session Ticket RFC 5077 hint 300 seconds, session tickets keys seems to be
rotated < daily
 SSL Session ID support       yes
```

**Comment by matteounitn** [comment]
Since we don't know where the result might break, i have a _less elegant_ but working regex:

```
    #3SHAKE
    if ! grep -Pzq "e\s*x\s*t\s*e\s*n\s*d\s*e\s*d\s*m\s*a\s*s\s*t\s*e\s*r\s*s\s*e\s*c\s*r\s*e\s*t\s*/\s*#\s*2\s*3" $toolReports/testssl_report.txt ; then
        echo "3SHAKE">> $root_folder/vulnerabilityList.txt
        echo "- detected: 3SHAKE"
    fi
```

Could you kindly try this on your use case by editing the file `Evaluator/enumerator.sh`?

Let me know if it works.

**Comment by pm-cfs** [comment]
Yes, that works.
FYI, the lines breaks seem tied to the console width; I tried with a different console and didn't get the same line breaks. Normally html2text breaks on word boundaries, but seems like there could be a situation where it would break inside a word so your RegEx is probably the safest option.
I re-ran with the default console and did get the same break and was able to verify that this RegEx works in my original case.
Thank you.

**Comment by matteounitn** [comment]
I will create a PR and discuss it with my colleagues to integrate the improvement into the code. 

We are currently working on a more powerful and performant TLSA version, so this will remain a hotfix until the new release.
